// system.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module system (
		input  wire        clk_clk,                           //                         clk.clk
		output wire        img_load_export,                   //                    img_load.export
		output wire [12:0] new_sdram_controller_0_wire_addr,  // new_sdram_controller_0_wire.addr
		output wire [1:0]  new_sdram_controller_0_wire_ba,    //                            .ba
		output wire        new_sdram_controller_0_wire_cas_n, //                            .cas_n
		output wire        new_sdram_controller_0_wire_cke,   //                            .cke
		output wire        new_sdram_controller_0_wire_cs_n,  //                            .cs_n
		inout  wire [15:0] new_sdram_controller_0_wire_dq,    //                            .dq
		output wire [1:0]  new_sdram_controller_0_wire_dqm,   //                            .dqm
		output wire        new_sdram_controller_0_wire_ras_n, //                            .ras_n
		output wire        new_sdram_controller_0_wire_we_n,  //                            .we_n
		output wire [1:0]  pio_mode_export,                   //                    pio_mode.export
		input  wire [9:0]  pio_sw_export,                     //                      pio_sw.export
		output wire [7:0]  pio_threshold_export,              //               pio_threshold.export
		input  wire        reset_reset_n,                     //                       reset.reset_n
		output wire        sdram_read_bridge_waitrequest,     //           sdram_read_bridge.waitrequest
		output wire [15:0] sdram_read_bridge_readdata,        //                            .readdata
		output wire        sdram_read_bridge_readdatavalid,   //                            .readdatavalid
		input  wire [0:0]  sdram_read_bridge_burstcount,      //                            .burstcount
		input  wire [15:0] sdram_read_bridge_writedata,       //                            .writedata
		input  wire [25:0] sdram_read_bridge_address,         //                            .address
		input  wire        sdram_read_bridge_write,           //                            .write
		input  wire        sdram_read_bridge_read,            //                            .read
		input  wire [1:0]  sdram_read_bridge_byteenable,      //                            .byteenable
		input  wire        sdram_read_bridge_debugaccess,     //                            .debugaccess
		output wire        sdram_write_bridge_waitrequest,    //          sdram_write_bridge.waitrequest
		output wire [15:0] sdram_write_bridge_readdata,       //                            .readdata
		output wire        sdram_write_bridge_readdatavalid,  //                            .readdatavalid
		input  wire [0:0]  sdram_write_bridge_burstcount,     //                            .burstcount
		input  wire [15:0] sdram_write_bridge_writedata,      //                            .writedata
		input  wire [25:0] sdram_write_bridge_address,        //                            .address
		input  wire        sdram_write_bridge_write,          //                            .write
		input  wire        sdram_write_bridge_read,           //                            .read
		input  wire [1:0]  sdram_write_bridge_byteenable,     //                            .byteenable
		input  wire        sdram_write_bridge_debugaccess     //                            .debugaccess
	);

	wire  [31:0] nios2_gen2_0_data_master_readdata;                           // mm_interconnect_0:nios2_gen2_0_data_master_readdata -> nios2_gen2_0:d_readdata
	wire         nios2_gen2_0_data_master_waitrequest;                        // mm_interconnect_0:nios2_gen2_0_data_master_waitrequest -> nios2_gen2_0:d_waitrequest
	wire         nios2_gen2_0_data_master_debugaccess;                        // nios2_gen2_0:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:nios2_gen2_0_data_master_debugaccess
	wire  [26:0] nios2_gen2_0_data_master_address;                            // nios2_gen2_0:d_address -> mm_interconnect_0:nios2_gen2_0_data_master_address
	wire   [3:0] nios2_gen2_0_data_master_byteenable;                         // nios2_gen2_0:d_byteenable -> mm_interconnect_0:nios2_gen2_0_data_master_byteenable
	wire         nios2_gen2_0_data_master_read;                               // nios2_gen2_0:d_read -> mm_interconnect_0:nios2_gen2_0_data_master_read
	wire         nios2_gen2_0_data_master_write;                              // nios2_gen2_0:d_write -> mm_interconnect_0:nios2_gen2_0_data_master_write
	wire  [31:0] nios2_gen2_0_data_master_writedata;                          // nios2_gen2_0:d_writedata -> mm_interconnect_0:nios2_gen2_0_data_master_writedata
	wire         mm_bridge_write_m0_waitrequest;                              // mm_interconnect_0:mm_bridge_write_m0_waitrequest -> mm_bridge_write:m0_waitrequest
	wire  [15:0] mm_bridge_write_m0_readdata;                                 // mm_interconnect_0:mm_bridge_write_m0_readdata -> mm_bridge_write:m0_readdata
	wire         mm_bridge_write_m0_debugaccess;                              // mm_bridge_write:m0_debugaccess -> mm_interconnect_0:mm_bridge_write_m0_debugaccess
	wire  [25:0] mm_bridge_write_m0_address;                                  // mm_bridge_write:m0_address -> mm_interconnect_0:mm_bridge_write_m0_address
	wire         mm_bridge_write_m0_read;                                     // mm_bridge_write:m0_read -> mm_interconnect_0:mm_bridge_write_m0_read
	wire   [1:0] mm_bridge_write_m0_byteenable;                               // mm_bridge_write:m0_byteenable -> mm_interconnect_0:mm_bridge_write_m0_byteenable
	wire         mm_bridge_write_m0_readdatavalid;                            // mm_interconnect_0:mm_bridge_write_m0_readdatavalid -> mm_bridge_write:m0_readdatavalid
	wire  [15:0] mm_bridge_write_m0_writedata;                                // mm_bridge_write:m0_writedata -> mm_interconnect_0:mm_bridge_write_m0_writedata
	wire         mm_bridge_write_m0_write;                                    // mm_bridge_write:m0_write -> mm_interconnect_0:mm_bridge_write_m0_write
	wire   [0:0] mm_bridge_write_m0_burstcount;                               // mm_bridge_write:m0_burstcount -> mm_interconnect_0:mm_bridge_write_m0_burstcount
	wire         mm_bridge_read_m0_waitrequest;                               // mm_interconnect_0:mm_bridge_read_m0_waitrequest -> mm_bridge_read:m0_waitrequest
	wire  [15:0] mm_bridge_read_m0_readdata;                                  // mm_interconnect_0:mm_bridge_read_m0_readdata -> mm_bridge_read:m0_readdata
	wire         mm_bridge_read_m0_debugaccess;                               // mm_bridge_read:m0_debugaccess -> mm_interconnect_0:mm_bridge_read_m0_debugaccess
	wire  [25:0] mm_bridge_read_m0_address;                                   // mm_bridge_read:m0_address -> mm_interconnect_0:mm_bridge_read_m0_address
	wire         mm_bridge_read_m0_read;                                      // mm_bridge_read:m0_read -> mm_interconnect_0:mm_bridge_read_m0_read
	wire   [1:0] mm_bridge_read_m0_byteenable;                                // mm_bridge_read:m0_byteenable -> mm_interconnect_0:mm_bridge_read_m0_byteenable
	wire         mm_bridge_read_m0_readdatavalid;                             // mm_interconnect_0:mm_bridge_read_m0_readdatavalid -> mm_bridge_read:m0_readdatavalid
	wire  [15:0] mm_bridge_read_m0_writedata;                                 // mm_bridge_read:m0_writedata -> mm_interconnect_0:mm_bridge_read_m0_writedata
	wire         mm_bridge_read_m0_write;                                     // mm_bridge_read:m0_write -> mm_interconnect_0:mm_bridge_read_m0_write
	wire   [0:0] mm_bridge_read_m0_burstcount;                                // mm_bridge_read:m0_burstcount -> mm_interconnect_0:mm_bridge_read_m0_burstcount
	wire  [31:0] nios2_gen2_0_instruction_master_readdata;                    // mm_interconnect_0:nios2_gen2_0_instruction_master_readdata -> nios2_gen2_0:i_readdata
	wire         nios2_gen2_0_instruction_master_waitrequest;                 // mm_interconnect_0:nios2_gen2_0_instruction_master_waitrequest -> nios2_gen2_0:i_waitrequest
	wire  [26:0] nios2_gen2_0_instruction_master_address;                     // nios2_gen2_0:i_address -> mm_interconnect_0:nios2_gen2_0_instruction_master_address
	wire         nios2_gen2_0_instruction_master_read;                        // nios2_gen2_0:i_read -> mm_interconnect_0:nios2_gen2_0_instruction_master_read
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;    // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest; // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_sysid_qsys_0_control_slave_readdata;       // sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sysid_qsys_0_control_slave_address;        // mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata;     // nios2_gen2_0:debug_mem_slave_readdata -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest;  // nios2_gen2_0:debug_mem_slave_waitrequest -> mm_interconnect_0:nios2_gen2_0_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess;  // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_debugaccess -> nios2_gen2_0:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address;      // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_address -> nios2_gen2_0:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read;         // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_read -> nios2_gen2_0:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable;   // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_byteenable -> nios2_gen2_0:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write;        // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_write -> nios2_gen2_0:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata;    // mm_interconnect_0:nios2_gen2_0_debug_mem_slave_writedata -> nios2_gen2_0:debug_mem_slave_writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_chipselect;            // mm_interconnect_0:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;              // onchip_memory2_0:readdata -> mm_interconnect_0:onchip_memory2_0_s1_readdata
	wire  [12:0] mm_interconnect_0_onchip_memory2_0_s1_address;               // mm_interconnect_0:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire   [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;            // mm_interconnect_0:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire         mm_interconnect_0_onchip_memory2_0_s1_write;                 // mm_interconnect_0:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;             // mm_interconnect_0:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_clken;                 // mm_interconnect_0:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire  [31:0] mm_interconnect_0_pio_sw_s1_readdata;                        // pio_sw:readdata -> mm_interconnect_0:pio_sw_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_sw_s1_address;                         // mm_interconnect_0:pio_sw_s1_address -> pio_sw:address
	wire         mm_interconnect_0_pio_threshold_s1_chipselect;               // mm_interconnect_0:pio_threshold_s1_chipselect -> pio_threshold:chipselect
	wire  [31:0] mm_interconnect_0_pio_threshold_s1_readdata;                 // pio_threshold:readdata -> mm_interconnect_0:pio_threshold_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_threshold_s1_address;                  // mm_interconnect_0:pio_threshold_s1_address -> pio_threshold:address
	wire         mm_interconnect_0_pio_threshold_s1_write;                    // mm_interconnect_0:pio_threshold_s1_write -> pio_threshold:write_n
	wire  [31:0] mm_interconnect_0_pio_threshold_s1_writedata;                // mm_interconnect_0:pio_threshold_s1_writedata -> pio_threshold:writedata
	wire         mm_interconnect_0_pio_mode_s1_chipselect;                    // mm_interconnect_0:pio_mode_s1_chipselect -> pio_mode:chipselect
	wire  [31:0] mm_interconnect_0_pio_mode_s1_readdata;                      // pio_mode:readdata -> mm_interconnect_0:pio_mode_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_mode_s1_address;                       // mm_interconnect_0:pio_mode_s1_address -> pio_mode:address
	wire         mm_interconnect_0_pio_mode_s1_write;                         // mm_interconnect_0:pio_mode_s1_write -> pio_mode:write_n
	wire  [31:0] mm_interconnect_0_pio_mode_s1_writedata;                     // mm_interconnect_0:pio_mode_s1_writedata -> pio_mode:writedata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_chipselect;      // mm_interconnect_0:new_sdram_controller_0_s1_chipselect -> new_sdram_controller_0:az_cs
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_readdata;        // new_sdram_controller_0:za_data -> mm_interconnect_0:new_sdram_controller_0_s1_readdata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_waitrequest;     // new_sdram_controller_0:za_waitrequest -> mm_interconnect_0:new_sdram_controller_0_s1_waitrequest
	wire  [24:0] mm_interconnect_0_new_sdram_controller_0_s1_address;         // mm_interconnect_0:new_sdram_controller_0_s1_address -> new_sdram_controller_0:az_addr
	wire         mm_interconnect_0_new_sdram_controller_0_s1_read;            // mm_interconnect_0:new_sdram_controller_0_s1_read -> new_sdram_controller_0:az_rd_n
	wire   [1:0] mm_interconnect_0_new_sdram_controller_0_s1_byteenable;      // mm_interconnect_0:new_sdram_controller_0_s1_byteenable -> new_sdram_controller_0:az_be_n
	wire         mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid;   // new_sdram_controller_0:za_valid -> mm_interconnect_0:new_sdram_controller_0_s1_readdatavalid
	wire         mm_interconnect_0_new_sdram_controller_0_s1_write;           // mm_interconnect_0:new_sdram_controller_0_s1_write -> new_sdram_controller_0:az_wr_n
	wire  [15:0] mm_interconnect_0_new_sdram_controller_0_s1_writedata;       // mm_interconnect_0:new_sdram_controller_0_s1_writedata -> new_sdram_controller_0:az_data
	wire         mm_interconnect_0_pio_img_load_s1_chipselect;                // mm_interconnect_0:pio_img_load_s1_chipselect -> pio_img_load:chipselect
	wire  [31:0] mm_interconnect_0_pio_img_load_s1_readdata;                  // pio_img_load:readdata -> mm_interconnect_0:pio_img_load_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_img_load_s1_address;                   // mm_interconnect_0:pio_img_load_s1_address -> pio_img_load:address
	wire         mm_interconnect_0_pio_img_load_s1_write;                     // mm_interconnect_0:pio_img_load_s1_write -> pio_img_load:write_n
	wire  [31:0] mm_interconnect_0_pio_img_load_s1_writedata;                 // mm_interconnect_0:pio_img_load_s1_writedata -> pio_img_load:writedata
	wire         irq_mapper_receiver0_irq;                                    // jtag_uart_0:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_gen2_0_irq_irq;                                        // irq_mapper:sender_irq -> nios2_gen2_0:irq
	wire         rst_controller_reset_out_reset;                              // rst_controller:reset_out -> [irq_mapper:reset, jtag_uart_0:rst_n, mm_bridge_read:reset, mm_bridge_write:reset, mm_interconnect_0:nios2_gen2_0_reset_reset_bridge_in_reset_reset, new_sdram_controller_0:reset_n, nios2_gen2_0:reset_n, pio_img_load:reset_n, pio_mode:reset_n, pio_sw:reset_n, pio_threshold:reset_n, rst_translator:in_reset, sysid_qsys_0:reset_n]
	wire         rst_controller_reset_out_reset_req;                          // rst_controller:reset_req -> [nios2_gen2_0:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                          // rst_controller_001:reset_out -> [mm_interconnect_0:onchip_memory2_0_reset1_reset_bridge_in_reset_reset, onchip_memory2_0:reset]
	wire         rst_controller_001_reset_out_reset_req;                      // rst_controller_001:reset_req -> onchip_memory2_0:reset_req
	wire         nios2_gen2_0_debug_reset_request_reset;                      // nios2_gen2_0:debug_reset_request -> rst_controller_001:reset_in1

	system_jtag_uart_0 jtag_uart_0 (
		.clk            (clk_clk),                                                     //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                     //               irq.irq
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (26),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_read (
		.clk              (clk_clk),                         //   clk.clk
		.reset            (rst_controller_reset_out_reset),  // reset.reset
		.s0_waitrequest   (sdram_read_bridge_waitrequest),   //    s0.waitrequest
		.s0_readdata      (sdram_read_bridge_readdata),      //      .readdata
		.s0_readdatavalid (sdram_read_bridge_readdatavalid), //      .readdatavalid
		.s0_burstcount    (sdram_read_bridge_burstcount),    //      .burstcount
		.s0_writedata     (sdram_read_bridge_writedata),     //      .writedata
		.s0_address       (sdram_read_bridge_address),       //      .address
		.s0_write         (sdram_read_bridge_write),         //      .write
		.s0_read          (sdram_read_bridge_read),          //      .read
		.s0_byteenable    (sdram_read_bridge_byteenable),    //      .byteenable
		.s0_debugaccess   (sdram_read_bridge_debugaccess),   //      .debugaccess
		.m0_waitrequest   (mm_bridge_read_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (mm_bridge_read_m0_readdata),      //      .readdata
		.m0_readdatavalid (mm_bridge_read_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (mm_bridge_read_m0_burstcount),    //      .burstcount
		.m0_writedata     (mm_bridge_read_m0_writedata),     //      .writedata
		.m0_address       (mm_bridge_read_m0_address),       //      .address
		.m0_write         (mm_bridge_read_m0_write),         //      .write
		.m0_read          (mm_bridge_read_m0_read),          //      .read
		.m0_byteenable    (mm_bridge_read_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (mm_bridge_read_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                // (terminated)
		.m0_response      (2'b00)                            // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (26),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mm_bridge_write (
		.clk              (clk_clk),                          //   clk.clk
		.reset            (rst_controller_reset_out_reset),   // reset.reset
		.s0_waitrequest   (sdram_write_bridge_waitrequest),   //    s0.waitrequest
		.s0_readdata      (sdram_write_bridge_readdata),      //      .readdata
		.s0_readdatavalid (sdram_write_bridge_readdatavalid), //      .readdatavalid
		.s0_burstcount    (sdram_write_bridge_burstcount),    //      .burstcount
		.s0_writedata     (sdram_write_bridge_writedata),     //      .writedata
		.s0_address       (sdram_write_bridge_address),       //      .address
		.s0_write         (sdram_write_bridge_write),         //      .write
		.s0_read          (sdram_write_bridge_read),          //      .read
		.s0_byteenable    (sdram_write_bridge_byteenable),    //      .byteenable
		.s0_debugaccess   (sdram_write_bridge_debugaccess),   //      .debugaccess
		.m0_waitrequest   (mm_bridge_write_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (mm_bridge_write_m0_readdata),      //      .readdata
		.m0_readdatavalid (mm_bridge_write_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (mm_bridge_write_m0_burstcount),    //      .burstcount
		.m0_writedata     (mm_bridge_write_m0_writedata),     //      .writedata
		.m0_address       (mm_bridge_write_m0_address),       //      .address
		.m0_write         (mm_bridge_write_m0_write),         //      .write
		.m0_read          (mm_bridge_write_m0_read),          //      .read
		.m0_byteenable    (mm_bridge_write_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (mm_bridge_write_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                 // (terminated)
		.m0_response      (2'b00)                             // (terminated)
	);

	system_new_sdram_controller_0 new_sdram_controller_0 (
		.clk            (clk_clk),                                                   //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),                           // reset.reset_n
		.az_addr        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_new_sdram_controller_0_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_new_sdram_controller_0_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_new_sdram_controller_0_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //      .waitrequest
		.zs_addr        (new_sdram_controller_0_wire_addr),                          //  wire.export
		.zs_ba          (new_sdram_controller_0_wire_ba),                            //      .export
		.zs_cas_n       (new_sdram_controller_0_wire_cas_n),                         //      .export
		.zs_cke         (new_sdram_controller_0_wire_cke),                           //      .export
		.zs_cs_n        (new_sdram_controller_0_wire_cs_n),                          //      .export
		.zs_dq          (new_sdram_controller_0_wire_dq),                            //      .export
		.zs_dqm         (new_sdram_controller_0_wire_dqm),                           //      .export
		.zs_ras_n       (new_sdram_controller_0_wire_ras_n),                         //      .export
		.zs_we_n        (new_sdram_controller_0_wire_we_n)                           //      .export
	);

	system_nios2_gen2_0 nios2_gen2_0 (
		.clk                                 (clk_clk),                                                    //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                            //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                         //                          .reset_req
		.d_address                           (nios2_gen2_0_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_gen2_0_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_gen2_0_data_master_read),                              //                          .read
		.d_readdata                          (nios2_gen2_0_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_gen2_0_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_gen2_0_data_master_write),                             //                          .write
		.d_writedata                         (nios2_gen2_0_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_gen2_0_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_gen2_0_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_gen2_0_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_gen2_0_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_gen2_0_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_gen2_0_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_gen2_0_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                            // custom_instruction_master.readra
	);

	system_onchip_memory2_0 onchip_memory2_0 (
		.clk        (clk_clk),                                          //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_001_reset_out_reset),               // reset1.reset
		.reset_req  (rst_controller_001_reset_out_reset_req),           //       .reset_req
		.freeze     (1'b0)                                              // (terminated)
	);

	system_pio_img_load pio_img_load (
		.clk        (clk_clk),                                      //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),              //               reset.reset_n
		.address    (mm_interconnect_0_pio_img_load_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_img_load_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_img_load_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_img_load_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_img_load_s1_readdata),   //                    .readdata
		.out_port   (img_load_export)                               // external_connection.export
	);

	system_pio_mode pio_mode (
		.clk        (clk_clk),                                  //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address    (mm_interconnect_0_pio_mode_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_mode_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_mode_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_mode_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_mode_s1_readdata),   //                    .readdata
		.out_port   (pio_mode_export)                           // external_connection.export
	);

	system_pio_sw pio_sw (
		.clk      (clk_clk),                              //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address  (mm_interconnect_0_pio_sw_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_sw_s1_readdata), //                    .readdata
		.in_port  (pio_sw_export)                         // external_connection.export
	);

	system_pio_threshold pio_threshold (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_pio_threshold_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_pio_threshold_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_pio_threshold_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_pio_threshold_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_pio_threshold_s1_readdata),   //                    .readdata
		.out_port   (pio_threshold_export)                           // external_connection.export
	);

	system_sysid_qsys_0 sysid_qsys_0 (
		.clock    (clk_clk),                                               //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                       //         reset.reset_n
		.readdata (mm_interconnect_0_sysid_qsys_0_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sysid_qsys_0_control_slave_address)   //              .address
	);

	system_mm_interconnect_0 mm_interconnect_0 (
		.clock_clk_clk                                       (clk_clk),                                                     //                                     clock_clk.clk
		.nios2_gen2_0_reset_reset_bridge_in_reset_reset      (rst_controller_reset_out_reset),                              //      nios2_gen2_0_reset_reset_bridge_in_reset.reset
		.onchip_memory2_0_reset1_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                          // onchip_memory2_0_reset1_reset_bridge_in_reset.reset
		.mm_bridge_read_m0_address                           (mm_bridge_read_m0_address),                                   //                             mm_bridge_read_m0.address
		.mm_bridge_read_m0_waitrequest                       (mm_bridge_read_m0_waitrequest),                               //                                              .waitrequest
		.mm_bridge_read_m0_burstcount                        (mm_bridge_read_m0_burstcount),                                //                                              .burstcount
		.mm_bridge_read_m0_byteenable                        (mm_bridge_read_m0_byteenable),                                //                                              .byteenable
		.mm_bridge_read_m0_read                              (mm_bridge_read_m0_read),                                      //                                              .read
		.mm_bridge_read_m0_readdata                          (mm_bridge_read_m0_readdata),                                  //                                              .readdata
		.mm_bridge_read_m0_readdatavalid                     (mm_bridge_read_m0_readdatavalid),                             //                                              .readdatavalid
		.mm_bridge_read_m0_write                             (mm_bridge_read_m0_write),                                     //                                              .write
		.mm_bridge_read_m0_writedata                         (mm_bridge_read_m0_writedata),                                 //                                              .writedata
		.mm_bridge_read_m0_debugaccess                       (mm_bridge_read_m0_debugaccess),                               //                                              .debugaccess
		.mm_bridge_write_m0_address                          (mm_bridge_write_m0_address),                                  //                            mm_bridge_write_m0.address
		.mm_bridge_write_m0_waitrequest                      (mm_bridge_write_m0_waitrequest),                              //                                              .waitrequest
		.mm_bridge_write_m0_burstcount                       (mm_bridge_write_m0_burstcount),                               //                                              .burstcount
		.mm_bridge_write_m0_byteenable                       (mm_bridge_write_m0_byteenable),                               //                                              .byteenable
		.mm_bridge_write_m0_read                             (mm_bridge_write_m0_read),                                     //                                              .read
		.mm_bridge_write_m0_readdata                         (mm_bridge_write_m0_readdata),                                 //                                              .readdata
		.mm_bridge_write_m0_readdatavalid                    (mm_bridge_write_m0_readdatavalid),                            //                                              .readdatavalid
		.mm_bridge_write_m0_write                            (mm_bridge_write_m0_write),                                    //                                              .write
		.mm_bridge_write_m0_writedata                        (mm_bridge_write_m0_writedata),                                //                                              .writedata
		.mm_bridge_write_m0_debugaccess                      (mm_bridge_write_m0_debugaccess),                              //                                              .debugaccess
		.nios2_gen2_0_data_master_address                    (nios2_gen2_0_data_master_address),                            //                      nios2_gen2_0_data_master.address
		.nios2_gen2_0_data_master_waitrequest                (nios2_gen2_0_data_master_waitrequest),                        //                                              .waitrequest
		.nios2_gen2_0_data_master_byteenable                 (nios2_gen2_0_data_master_byteenable),                         //                                              .byteenable
		.nios2_gen2_0_data_master_read                       (nios2_gen2_0_data_master_read),                               //                                              .read
		.nios2_gen2_0_data_master_readdata                   (nios2_gen2_0_data_master_readdata),                           //                                              .readdata
		.nios2_gen2_0_data_master_write                      (nios2_gen2_0_data_master_write),                              //                                              .write
		.nios2_gen2_0_data_master_writedata                  (nios2_gen2_0_data_master_writedata),                          //                                              .writedata
		.nios2_gen2_0_data_master_debugaccess                (nios2_gen2_0_data_master_debugaccess),                        //                                              .debugaccess
		.nios2_gen2_0_instruction_master_address             (nios2_gen2_0_instruction_master_address),                     //               nios2_gen2_0_instruction_master.address
		.nios2_gen2_0_instruction_master_waitrequest         (nios2_gen2_0_instruction_master_waitrequest),                 //                                              .waitrequest
		.nios2_gen2_0_instruction_master_read                (nios2_gen2_0_instruction_master_read),                        //                                              .read
		.nios2_gen2_0_instruction_master_readdata            (nios2_gen2_0_instruction_master_readdata),                    //                                              .readdata
		.jtag_uart_0_avalon_jtag_slave_address               (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                 jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write                 (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),       //                                              .write
		.jtag_uart_0_avalon_jtag_slave_read                  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),        //                                              .read
		.jtag_uart_0_avalon_jtag_slave_readdata              (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                                              .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata             (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                                              .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest           (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                                              .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect            (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  //                                              .chipselect
		.new_sdram_controller_0_s1_address                   (mm_interconnect_0_new_sdram_controller_0_s1_address),         //                     new_sdram_controller_0_s1.address
		.new_sdram_controller_0_s1_write                     (mm_interconnect_0_new_sdram_controller_0_s1_write),           //                                              .write
		.new_sdram_controller_0_s1_read                      (mm_interconnect_0_new_sdram_controller_0_s1_read),            //                                              .read
		.new_sdram_controller_0_s1_readdata                  (mm_interconnect_0_new_sdram_controller_0_s1_readdata),        //                                              .readdata
		.new_sdram_controller_0_s1_writedata                 (mm_interconnect_0_new_sdram_controller_0_s1_writedata),       //                                              .writedata
		.new_sdram_controller_0_s1_byteenable                (mm_interconnect_0_new_sdram_controller_0_s1_byteenable),      //                                              .byteenable
		.new_sdram_controller_0_s1_readdatavalid             (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid),   //                                              .readdatavalid
		.new_sdram_controller_0_s1_waitrequest               (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),     //                                              .waitrequest
		.new_sdram_controller_0_s1_chipselect                (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),      //                                              .chipselect
		.nios2_gen2_0_debug_mem_slave_address                (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_address),      //                  nios2_gen2_0_debug_mem_slave.address
		.nios2_gen2_0_debug_mem_slave_write                  (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_write),        //                                              .write
		.nios2_gen2_0_debug_mem_slave_read                   (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_read),         //                                              .read
		.nios2_gen2_0_debug_mem_slave_readdata               (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_readdata),     //                                              .readdata
		.nios2_gen2_0_debug_mem_slave_writedata              (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_writedata),    //                                              .writedata
		.nios2_gen2_0_debug_mem_slave_byteenable             (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_byteenable),   //                                              .byteenable
		.nios2_gen2_0_debug_mem_slave_waitrequest            (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_waitrequest),  //                                              .waitrequest
		.nios2_gen2_0_debug_mem_slave_debugaccess            (mm_interconnect_0_nios2_gen2_0_debug_mem_slave_debugaccess),  //                                              .debugaccess
		.onchip_memory2_0_s1_address                         (mm_interconnect_0_onchip_memory2_0_s1_address),               //                           onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                           (mm_interconnect_0_onchip_memory2_0_s1_write),                 //                                              .write
		.onchip_memory2_0_s1_readdata                        (mm_interconnect_0_onchip_memory2_0_s1_readdata),              //                                              .readdata
		.onchip_memory2_0_s1_writedata                       (mm_interconnect_0_onchip_memory2_0_s1_writedata),             //                                              .writedata
		.onchip_memory2_0_s1_byteenable                      (mm_interconnect_0_onchip_memory2_0_s1_byteenable),            //                                              .byteenable
		.onchip_memory2_0_s1_chipselect                      (mm_interconnect_0_onchip_memory2_0_s1_chipselect),            //                                              .chipselect
		.onchip_memory2_0_s1_clken                           (mm_interconnect_0_onchip_memory2_0_s1_clken),                 //                                              .clken
		.pio_img_load_s1_address                             (mm_interconnect_0_pio_img_load_s1_address),                   //                               pio_img_load_s1.address
		.pio_img_load_s1_write                               (mm_interconnect_0_pio_img_load_s1_write),                     //                                              .write
		.pio_img_load_s1_readdata                            (mm_interconnect_0_pio_img_load_s1_readdata),                  //                                              .readdata
		.pio_img_load_s1_writedata                           (mm_interconnect_0_pio_img_load_s1_writedata),                 //                                              .writedata
		.pio_img_load_s1_chipselect                          (mm_interconnect_0_pio_img_load_s1_chipselect),                //                                              .chipselect
		.pio_mode_s1_address                                 (mm_interconnect_0_pio_mode_s1_address),                       //                                   pio_mode_s1.address
		.pio_mode_s1_write                                   (mm_interconnect_0_pio_mode_s1_write),                         //                                              .write
		.pio_mode_s1_readdata                                (mm_interconnect_0_pio_mode_s1_readdata),                      //                                              .readdata
		.pio_mode_s1_writedata                               (mm_interconnect_0_pio_mode_s1_writedata),                     //                                              .writedata
		.pio_mode_s1_chipselect                              (mm_interconnect_0_pio_mode_s1_chipselect),                    //                                              .chipselect
		.pio_sw_s1_address                                   (mm_interconnect_0_pio_sw_s1_address),                         //                                     pio_sw_s1.address
		.pio_sw_s1_readdata                                  (mm_interconnect_0_pio_sw_s1_readdata),                        //                                              .readdata
		.pio_threshold_s1_address                            (mm_interconnect_0_pio_threshold_s1_address),                  //                              pio_threshold_s1.address
		.pio_threshold_s1_write                              (mm_interconnect_0_pio_threshold_s1_write),                    //                                              .write
		.pio_threshold_s1_readdata                           (mm_interconnect_0_pio_threshold_s1_readdata),                 //                                              .readdata
		.pio_threshold_s1_writedata                          (mm_interconnect_0_pio_threshold_s1_writedata),                //                                              .writedata
		.pio_threshold_s1_chipselect                         (mm_interconnect_0_pio_threshold_s1_chipselect),               //                                              .chipselect
		.sysid_qsys_0_control_slave_address                  (mm_interconnect_0_sysid_qsys_0_control_slave_address),        //                    sysid_qsys_0_control_slave.address
		.sysid_qsys_0_control_slave_readdata                 (mm_interconnect_0_sysid_qsys_0_control_slave_readdata)        //                                              .readdata
	);

	system_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_gen2_0_irq_irq)            //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                         // reset_in0.reset
		.reset_in1      (nios2_gen2_0_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
